/* eslint-disable import/prefer-default-export */
const GET_INPUT = "GET_INPUT"
const SIGN_IN = "SIGN_IN"
const SIGN_UP = "SIGN_UP"
const POST_GIF = "POST_GIF"
const POST_ARTICLE = "POST_ARTICLE"
const FEED = "FEED"
const GIF_DATA = "GIF_DATA"
const ARTICLE_DATA = "ARTICLE_DATA"
const EDITED_ARTICLE_DATA = "EDITED_ARTICLE_DATA"
const DELETE_ARTICLE = "DELETE_ARTICLE"
const DELETE_GIF = "DELETE_GIF"

export {
  GET_INPUT,
  SIGN_IN,
  SIGN_UP,
  POST_GIF,
  POST_ARTICLE,
  FEED,
  GIF_DATA,
  ARTICLE_DATA,
  EDITED_ARTICLE_DATA,
  DELETE_ARTICLE,
  DELETE_GIF
}
